version: '3.7'

services:
    backend:
      container_name: back_end
      build: .\simple-api-student-main\
      networks:
        - app-network
      depends_on:
        - database

    database:
      container_name: db
      build: .\TP_Docker\
      networks:
        - app-network

    httpd:
      container_name: front_end
      build: .\TP_Docker_HTTP\
      ports:
        - "8080:80"
      networks:
        - app-network
      depends_on:
        - backend

networks:
  app-network: